# Generated by Django 3.2.12 on 2022-03-15 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=50, verbose_name='用户昵称')),
                ('user_really_name', models.CharField(default='', max_length=10, verbose_name='用户姓名')),
                ('company_school', models.CharField(default='', max_length=50, verbose_name='机构')),
                ('sex', models.BooleanField(default='True', verbose_name='性别')),
                ('user_portrait', models.ImageField(null=True, upload_to='', verbose_name='头像')),
                ('address', models.CharField(default='', max_length=100, verbose_name='用户地址')),
            ],
            options={
                'verbose_name_plural': '用户信息',
                'db_table': 'userdata',
            },
        ),
        migrations.CreateModel(
            name='ExpressAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='中国', max_length=50, verbose_name='国家')),
                ('province', models.CharField(default='湖南', max_length=50, verbose_name='省份')),
                ('city', models.CharField(default='长沙', max_length=10, verbose_name='市')),
                ('area', models.CharField(default='', max_length=10, verbose_name='区/县')),
                ('street', models.CharField(default='', max_length=10, verbose_name='街道/镇')),
                ('name', models.CharField(default='', max_length=10, verbose_name='姓名')),
                ('phone', models.CharField(default=88888888888, max_length=11, verbose_name='电话')),
                ('user_data', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_page.userdata')),
            ],
            options={
                'verbose_name_plural': '地址信息',
                'db_table': 'express_address',
            },
        ),
    ]
