# Generated by Django 3.2.12 on 2022-03-15 03:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0002_auto_20220315_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountmoney',
            name='integral',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000000000)], verbose_name='积分'),
        ),
        migrations.AlterField(
            model_name='amountmoney',
            name='integral_consume',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000000000000)], verbose_name='积分开销'),
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(default='', max_length=200, verbose_name='商品名')),
                ('collection_data', models.DateField(auto_now_add=True, verbose_name='加入日期')),
                ('collection_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_page.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(default='', max_length=200, verbose_name='商品名')),
                ('collection_data', models.DateField(auto_now_add=True, verbose_name='收藏日期')),
                ('collection_time', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_page.userdata')),
            ],
        ),
    ]
