# Generated by Django 3.2.12 on 2022-03-15 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0003_auto_20220315_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodscollection',
            options={'verbose_name_plural': '用户收藏'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name_plural': '用户购物车'},
        ),
        migrations.AlterModelTable(
            name='goodscollection',
            table='goods_collection',
        ),
        migrations.AlterModelTable(
            name='shoppingcart',
            table='shopping_cart',
        ),
    ]
